name: design-tracker-template
markdown: kramdown
sass:
  style: compressed
exclude: [
  "deploy",
  "gemfile",
  "Gemfile.lock",
  "package.json",
  "gulpfile.js",
  "node_modules",
  "_site"
]
collections:
  documents_collection:
    output: true
    permalink: /:collection/:name
    defaults:
    scope:
      path: "./src/docs"
      type: documents
    values:
      author: "Red Hat UXD"
    layout: page
